### 회원가입 - 성공
POST localhost:8081/api/account/signup
Content-Type: application/json

{
    "email": "test1@test.com",
    "password": "test1234!",
    "name": "test1"
}

### 회원가입2 - 성공
POST localhost:8081/api/account/signup
Content-Type: application/json

{
  "email": "test2@test.com",
  "password": "test1234!",
  "name": "test2"
}

### 회원 로그인 조회
GET localhost:8081/api/account/account?email=test1@test.com

### 회원 정보 조회
GET localhost:8081/api/account/members
X-USER-ID: 1

### 로그인 성공 및 최근 로그인 시간 수정
PATCH localhost:8081/api/account/account/me
X-USER-ID: 1

### 회원 정보 수정 - password
PUT localhost:8081/api/account/members
Content-Type: application/json
X-USER-ID: 1

{
  "password": "test1234!@"
}

### 회원 정보 수정 - name
PUT localhost:8081/api/account/members
Content-Type: application/json
X-USER-ID: 1

{
  "name": "test101"
}

### 휴면 해제
PUT localhost:8081/api/account/members/1/active

### 회원 탈퇴
DELETE localhost:8081/api/account/members
X-USER-ID: 1

### 회원이름반환
GET localhost:8081/api/account/member
X-USER-ID: 1

### 회원 리스트 반환
POST localhost:8081/api/account/members/batch
Content-Type: application/json

{
  "ids": [1, 2]
}

### 회원 id반환
POST localhost:8081/api/account/members/id
Content-Type: application/json

{
  "email": "test1@test.com"
}